language: node_js

before_script: make bootstrap

script: make $JOB

matrix:
  fast_finish: true
  include:
    - node_js: "10"
      env: JOB=test-ci
    - node_js: "8"
      env: JOB=test-ci
    - node_js: "node"
      env: JOB=test-pnpm
      if: branch = master
