language: node_js

cache:
  yarn: true

before_install: npm i -g yarn
install: make bootstrap

script: make $JOB

matrix:
  include:
    - node_js: "10"
      env: JOB=test-ci
    - node_js: "8"
      env: JOB=test-ci
    - node_js: "node"
      env: JOB=test-pnpm
      if: branch = master

  allow_failures:
    - node_js: "node"
