init:
  - git config --global core.autocrlf true

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - choco install make
  - make bootstrap

test_script:
  - node --version
  - npm --version
  - make test-ci

environment:
  nodejs_version: "10"
